name: Release Kotlin SDK

on:
  workflow_dispatch:

  on:
   push:
     branches:
        - "release/**"

jobs:
  release:
    name: Build and Publish to Maven Central
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set Up JDK
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '11'
          cache: 'gradle'

      - name: Grant Execute Permission for Gradlew
        run: chmod +x gradlew

      - name: Gradle Sync
        run: ./gradlew dependencies

      - name: Build and Publish SDK
        run: ./gradlew :atlas-sdk:publishAndReleaseToMavenCentral --no-configuration-cache --stacktrace
        env:
          OSSRH_USERNAME: ${{ secrets.OSSRH_USERNAME }}
          OSSRH_PASSWORD: ${{ secrets.OSSRH_PASSWORD }}
          SIGNING_KEY: ${{ secrets.SIGNING_KEY }}
          SIGNING_PASSWORD: ${{ secrets.SIGNING_PASSWORD }}
