name: Release Kotlin SDK

on:
  push:
    branches:
      - 'release/**'
  pull_request:
    branches:
      - master

jobs:
  Build:
    # Skip build if commit message contains 'skip ci'
    if: "!contains(github.event.head_commit.message, 'skip ci')"

    runs-on: ubuntu-latest
    timeout-minutes: 30

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set Up JDK
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: 17

      - name: Make Gradle Executable
        run: chmod +x ./gradlew

      - name: Gradle Sync
        run: ./gradlew dependencies

      - name: Build SDK
        run: ./gradlew :atlas-sdk:assemble

  Upload2Maven:

    needs: Build

    runs-on: ubuntu-latest
    timeout-minutes: 30

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set Up JDK
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: 17

      - name: Make Gradle Executable
        run: chmod +x ./gradlew

      - name: Import GPG Key
        env:
          GPG_KEY: ${{ secrets.SIGNING_KEY }}
        run: |
          echo "$GPG_KEY" | base64 --decode | gpg --batch --import

      - name: Upload Library to Maven Central
        run: ./gradlew :atlas-sdk:publishAndReleaseToMavenCentral --no-configuration-cache --stacktrace --info
        env:
          ORG_GRADLE_PROJECT_signingInMemoryKey: ${{ secrets.SIGNING_KEY }}
          ORG_GRADLE_PROJECT_signingInMemoryKeyPassword: ${{ secrets.SIGNING_PASSWORD }}
          OSSRH_USERNAME: ${{ secrets.OSSRH_USERNAME }}
          OSSRH_PASSWORD: ${{ secrets.OSSRH_PASSWORD }}

